# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do canal')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandrini_test.Channel', verbose_name='Canal')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandrini_test.Product', verbose_name='Sub produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
