# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandrini_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandrini_test.Product', verbose_name='Sub produto'),
        ),
    ]
