# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandrini_test', '0002_auto_20160806_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandrini_test.Category', verbose_name='Top Categoria'),
        ),
    ]
