# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandrini_test', '0003_auto_20160806_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('channel', 'name', 'top_category')]),
        ),
    ]
